In [1]:
!pip install flurs

The directory '/Users/ivanmatis/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/ivanmatis/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.


In [2]:
from flurs.recommender.user_knn import UserKNNRecommender
from converter.converter import Converter
from flurs.data.entity import User, Item, Event
import numpy as np

'''
[Common]
Dataset: ML100k
Trial: 1

[Model]
Name: user-knn
Epoch: 1
'''
dataset = "ML100k"
k =  5


data = Converter().convert(dataset=dataset)

print (data.n_user)
print (data.n_item)
print (data.n_sample)
print (data.n_batch_train)
print (data.n_batch_test)
print (data.n_test)
print (len(data.ratings))
print (data.ratings[0])

print (data.ratings)
#list of events
print (len(data.samples))

#print (data.dts)




from flurs.recommender.mf import MFRecommender

recommender = MFRecommender(k=40)
#recommender = UserKNNRecommender(k=k)
#rec.initialize()
recommender.initialize()

items_indexes = []
evt_window01 = data.samples[:500]
for evt in evt_window01:
    print ("***")

    if recommender.is_new_user(evt.user.index):
        recommender.register_user(evt.user)
        #print (evt.user)
        print("new user")
        print (evt.user.index)

    if recommender.is_new_item(evt.item.index):
        recommender.register_item(evt.item)
        items_indexes.append(evt.item.index)
        #print (evt.item)
        print("new item")
        print (evt.item.index)

    #print (evt.value)
    #print (evt.context)
    recommender.update(evt)

print (recommender.users)
#print (recommender.items)

943
1682
100000
20000
10000
70000
100000
[      259       255         4 874724710]
[[      259       255         4 874724710]
 [      259       286         4 874724727]
 [      259       298         4 874724754]
 ..., 
 [      729       328         3 893286638]
 [      729       748         4 893286638]
 [      729       272         4 893286638]]
100000
***
new user
0
new item
0
***
new item
1
***
new item
2
***
new item
3
***
new item
4
***
new item
5
***
new item
6
***
new item
7
***
new item
8
***
new item
9
***
new item
10
***
new item
11
***
new item
12
***
new item
13
***
new item
14
***
new item
15
***
new user
1
new item
16
***
new item
17
***
new item
18
***
new item
19
***
new item
20
***
new item
21
***
new item
22
***
new item
23
***
new item
24
***
new item
25
***
new user
2
new item
26
***
new item
27
***
new item
28
***
new item
29
***
new item
30
***
new item
31
***
new item
32
***
new item
33
***
new item
34
***
new item
35
***
new item
36
***
new item
37
***
new item


## listado de candidados

In [3]:
from numpy  import array
candidates= array( items_indexes )
print("candidates")
print (candidates)








#  model, res = self.__run(create)

candidates
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243

## predicción usuario 1

In [4]:
print("************************")
user = evt_window01[0].user
#user = User(6)
print(user)
# specify target user and list of item candidates
#recs = recommender.recommend(user, np.array([0]))
recs = recommender.recommend(user, candidates )
print("recs")
print (recs)
score = recommender.score(user, candidates)
#print("score")
#print(score)

************************
User(index=0, feature=[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  0.])
recs
(array([173, 232, 104,  25,   4, 186, 217, 158, 179,  69,  18, 107, 279,
        80,  89, 204,  60, 159, 245, 102, 313, 331,  76,  34, 190, 178,
       153,  23, 224,  88,  33, 242, 124, 280, 299, 231, 281, 113, 256,
       125,  31,  46, 298, 261,  49,  21,  87, 289, 137, 201,  11, 161,
         2, 155, 259, 206,  55, 150, 269, 130, 315, 170, 265, 288, 182,
       152, 342,  72, 122,  20, 103, 329,  97,  43, 310,  64,  16, 343,
       164, 233, 110, 168, 142,  28, 311, 207, 334, 210, 148,   9, 237,
        61, 263, 243, 290, 295,  14, 144,  84, 195,  96, 131, 185, 320,
       154,  24, 105, 229, 308, 196, 117, 199,  82,   1, 172, 115, 230,
        40, 127,  29,  22,  12,  30,  53, 253, 247, 226,   0, 340,  94,
       297, 222,  51, 133,  98,  67, 277, 193,   3, 177, 282,  57, 236,
       325, 187, 333, 286, 116,  79, 324, 215, 258, 225, 32

## predicción usuario 2

In [5]:
print("************************")
print("************************")
user = evt_window01[300].user
print(user)
# specify target user and list of item candidates
recs = recommender.recommend(user, candidates)
print("recs")
print (recs)
#score = recommender.score(user, candidates)
#print("score")
#print(score)
print("************************")
print("************************")

************************
************************
User(index=3, feature=[ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
  0.  0.  0.  0.  0.])
recs
(array([ 57, 205, 305,  38, 240,  36, 220, 296, 135,   1, 166, 157, 312,
        62,  48,  19, 285, 318, 148, 239,  35,  86, 317, 155, 151, 287,
       202,  46,   8,  44, 221, 279,  77, 229,   0, 212,  56, 101, 169,
       280,  74, 120, 156,  87, 117, 218, 284, 174, 159, 311, 335, 321,
       180, 162, 327, 236,  75,  50, 116,  66, 213,  93,  80,  13, 206,
       210, 110,  37, 109, 282, 242, 123, 194, 269,  78,  98, 177, 260,
       306, 171, 307, 295, 326, 268, 201,  58, 302,  43,  24, 267, 262,
       102, 231, 246, 343,  42, 137, 112, 232, 266,  15, 344, 250,  97,
        29, 216,  33, 230, 226,  10, 132, 181,  83, 309, 224,  82, 125,
       324, 152, 122,  69,  68, 283, 272, 175, 241, 222,  12, 254, 290,
        47, 288, 316, 277, 186,  21, 255, 163, 219,  95, 121, 271, 143,
       293, 118, 178, 273,  90, 33